version: '3'

services: 

  nginx:
    image: nginx
    container_name: nginx
    links:
      - jenkins
      - gitlab
    volumes: 
      - ./nginx/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
      - ./nginx/gitlab.conf:/etc/nginx/conf.d/gitlab.conf
    ports:
     - 80:80

  jenkins:
    container_name: jenkins
    image: jenkins
    build: 
      dockerfile: jenkins/Dockerfile
      context: .
    environment:
      ENVSUBST_VARS: FQDN
      FQDN: localhost
    ports: 
      - 50000:50000
      - 8080:8080
    links: 
      - gitlab
    volumes: 
     - jenkins_data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    environment:
      ENVSUBST_VARS: FQDN
      FQDN: localhost
    volumes: 
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    restart: always
    ports:
      - 8100:8100

volumes: 
  jenkins_data: